# add food
POST http://localhost:5000/food
Content-Type: application/json

{
    "name"       : "Bread",
    "quantity"   : 1,
    "calories"   : 100,
    "expiration" : "07/10/2021",
    "store"      : 1
}

# add expired food
POST http://localhost:5000/food
Content-Type: application/json

{
    "name"       : "Tomato",
    "quantity"   : 1,
    "calories"   : 50,
    "expiration" : "03/10/1998",
    "store"      : 1
}


# get food
GET http://localhost:5000/food/1/1 HTTP/1.1
Content-Type: application/json

# change food
PUT http://localhost:5000/food/1/1 HTTP/1.1
Content-Type: application/json

{
    "name" : "Super Bread"
}


# delete food
DELETE http://localhost:5000/food/2/1 HTTP/1.1
Content-Type: application/json


# list all foods
GET http://localhost:5000/foods/1 HTTP/1.1
Content-Type: application/json

# send photo
POST http://localhost:5000/food/photo/upload HTTP/1.1
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; name="file"; filename="photo.png"
Content-Type: application/octet-stream

< .\food.png
--MyBoundary
Content-Disposition: form-data; name="food"

1
--MyBoundary--


# get photo
GET http://localhost:5000/food/photo/download/1 HTTP/1.1
Content-Type: application/json
