# add store
POST http://localhost:5000/store
Content-Type: application/json

{
    "name"     : "Walmart",
    "phone"    : "(800)999-9999-3939",
    "street"   : "2395 Peachtree Pkwy",
    "city"     : "Cumming",
    "state"    : "Georgia",
    "zipcode"  : 30041,
    "open"     : "09:00:00",
    "close"    : "23:00:00"
}

# get store
GET http://localhost:5000/store/2 HTTP/1.1
Content-Type: application/json

# change store
PUT http://localhost:5000/store/2 HTTP/1.1
Content-Type: application/json

{
    "name" : "Super Walmart"
}


# delete store
DELETE http://localhost:5000/store/3 HTTP/1.1
Content-Type: application/json


# list all stores
GET http://localhost:5000/stores HTTP/1.1
Content-Type: application/json