# register user
POST http://localhost:5000/register HTTP/1.1
Content-Type: application/json

{
    "password"   : "harvest",
    "email"      : "team-um6@gsu.edu", 
    "store"      : 2
}

# authenticate
POST http://localhost:5000/auth
Content-Type: application/json

{
    "email"    : "team-um6@gsu.edu",
    "password" : "harvest"
}

# user profile
GET http://localhost:5000/user/profile
Content-Type: application/json
Authorization: JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTgyNjY3ODYsImlhdCI6MTYxODI2NDk4NiwibmJmIjoxNjE4MjY0OTg2LCJpZGVudGl0eSI6MX0.9nO-5mHj4wJG2_fLs-BGhPZYTqd0yIv5i_dnJrBTEE0



# get user
GET http://localhost:5000/user/1/team-um6@gsu.edu HTTP/1.1
Content-Type: application/json


# change password
PUT http://localhost:5000/user/1/team-um6@gsu.edu HTTP/1.1
Content-Type: application/json

{
    "password" : "GSU"
}


# delete user
POST http://localhost:5000/register HTTP/1.1
Content-Type: application/json

{
    "password"   : "temp",
    "email"      : "temp@gsu.edu", 
    "store"      : 1
}

DELETE http://localhost:5000/user/1/temp@gsu.edu HTTP/1.1
Content-Type: application/json


# List users
GET http://localhost:5000/users/2 HTTP/1.1
Content-Type: application/json
Authorization: JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTU0MDE2NzEsImlhdCI6MTYxNTM5OTg3MSwibmJmIjoxNjE1Mzk5ODcxLCJpZGVudGl0eSI6MX0.HlnPRxv8qJewkMPb1JF6Muz-wx8KItpKWFZ9OZVVhco