# 1. User Registration (missing fields)
POST https://team-um6.herokuapp.com/register HTTP/1.1
Content-Type: application/json

{
    "email"      : "team-um6@gsu.edu", 
    "store"      : 10
}


# 2. User Registration (duplicate account)
POST https://team-um6.herokuapp.com/register HTTP/1.1
Content-Type: application/json

{
    "password"   : "secret",
    "email"      : "team-um6@gsu.edu", 
    "store"      : 10
}


# 3. User Registration (successful)
POST https://team-um6.herokuapp.com/register HTTP/1.1
Content-Type: application/json

{
    "password"   : "secret",
    "email"      : "team-um7@gsu.edu", 
    "store"      : 10
}